### ISSUE TITLE
XML error with "account.menu_finance_configuration" V14E

### ISSUE THREAD

**Issue by jcfernandez-890825** [odoo-ide/pycharm-odoo#10]
Pycharm is showing the following error:
![image](https://user-images.githubusercontent.com/28876647/131683217-57a819c5-6818-4cf4-99ac-4172b2ee3891.png)

In my \_\_manifest\_\_.py I have "account" as a dependency:
![image](https://user-images.githubusercontent.com/28876647/131683392-39573b9e-def6-4c00-971e-ca3acd0554d5.png)

`account.menu_finance_configuration` is defined in `src/odoo/odoo/addons/account/views/account_menuitem.xml`

Please help

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

I just discovered that Odoo supports recursive menuitem declaration (https://github.com/odoo/odoo/commit/c8063af7a085eda61e470fa5c861e94388429644). I will update the plugin to support this feature. Please wait for the fix in the next version. Thank you for reporting.

**Comment by jcfernandez-890825** [comment]
Thanks for the quick reply.
Again, this plugin is amazing, thumbs up.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

The new version 2021.2.5 has been released with the fix for this issue. Enjoy!

**Comment by jcfernandez-890825** [comment]
Thank you.
