### ISSUE TITLE
Type hint for recordset

### ISSUE THREAD

**Issue by trinhanhngoc** [odoo-ide/pycharm-odoo#12]
Requested by @tom10271 in https://github.com/trinhanhngoc/pycharm-odoo-old/issues/39

> Similar to `@var Product $product` in PHP. If it is not supported now can we have this in the future?

**Comment by jcfernandez-890825** [comment]
Hello @trinhanhngoc ,
Thanks for this feature.
Could you add some example code as guidance please?

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

The plugin currently support specific type hint for recordset arguments of a function:

**Case 1:** use model name as type

![Screenshot from 2021-09-07 23-24-03](https://user-images.githubusercontent.com/11208291/132378981-2b462d74-a3a7-407e-b3fa-f1a06c08ed7d.png)

**Case 2:** use a concrete class of model as type, the plugin will convert it to type of model to respect model inheritance.

![Screenshot from 2021-09-07 23-25-17](https://user-images.githubusercontent.com/11208291/132379114-7472e82f-53d7-4b53-8393-2e21f1369363.png)

In the next versions, I will improve type hint support to other contexts as variables,...

**Comment by jcfernandez-890825** [comment]
How about when putting several options as type hints?
![image](https://user-images.githubusercontent.com/28876647/137710202-9b26f47a-a02a-4627-9a2a-447e913eb8b9.png)

`sale.subscription.line or sale.subscription.renew.wizard.replace_option new_lines`

This seems to not be working.

**Comment by trinhanhngoc** [comment]
@jcfernandez-890825 Yes, complex types are not supported yet. I am still working to find a solution for this difficult problem.

**Comment by eselimsen** [comment]
Hi @trinhanhngoc 
Hope you're doing well.
Is there a progress on this?

**Comment by trinhanhngoc** [comment]
Hi @eselimsen . Thank you, I are still improving the plugin every day. However, this feature is not in the plan for the new release next month. I will revisit this feature later.  In the meantime, if you have any ideas about this feature, feel free to comment here.

**Comment by eselimsen** [comment]
Yes, the plugin gets better and better on each release, I re-love it each time thank you.
Looks like we'll have to wait for a while, thanks for the update.

**Comment by trinhanhngoc** [comment]
Related issues:
#67
#78
https://github.com/odoo/odoo/issues/21794
https://github.com/odoo/odoo/issues/89106

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 @eselimsen @mrm-david @tom10271 @ConorEganLE

Beside reworking [odoo-stubs](https://github.com/odoo-ide/odoo-stubs) for more complete type hints,  I am also implementing this much loved feature for the next version 2022.6. I need your opinions on my proposal for the syntax of type hint for recordset.

First, I think that any proper syntax should safisfy the following conditions:

- Is valid syntax for type hint annotation as specified in [PEP 484](https://peps.python.org/pep-0484/) and [PEP 563](https://peps.python.org/pep-0563/).
- Concise but clear.

In my previous comment https://github.com/odoo-ide/pycharm-odoo/issues/60#issuecomment-1013671264 I proposed the syntax `model:a.b.c` to specify type of `a.b.c` model. However, the colon `:` separator makes the expression `model:a.b.c` invalid. Therefore I propose the following alternative: `odoo.model.a_b_c` to specify type of `a.b.c` model. E.g:

- `odoo.model.res_partner`
- `odoo.model.res_partner | None`
- `tuple[odoo.model.res_partner, odoo.model.res_company]`
- `dict[str, odoo.model.res_partner]`
- ...

Because the object reference `odoo.model` actually doesn't exist, we need to wrap it in a string, e.g:

```python
def check_partner(self, partner: "odoo.model.res_partner | int"): pass
```

This way I can help IDEs understand it while avoiding runtime errors (postponed evaluation of annotations). In the future, if Odoo decides to improve the typing story of the odoo source code, they can turn `odoo.model` (or another name for the same purpose) into a real object. Then we can write a more concise syntax without quotes:

```python
def check_partner(self, partner: odoo.model.res_partner | int): pass
```

**Comment by jcfernandez-890825** [comment]
I like it. I can't wait to have this. Will it work when used like this?

```python
res = check_partner(self, partner)  # type: "odoo.model.res_partner | int"
```

```python
def check_partner(self, partner: "odoo.model.res_partner | int"):
        """
        :type vals: odoo.model.res_partner | int
        """
```

**Comment by trinhanhngoc** [comment]
@jcfernandez-890825 The syntax will be the same for both inline comment and docstring. So, the answer is YES.

**Comment by trinhanhngoc** [comment]
@jcfernandez-890825 For the inline comment and docstring, you can write it without quotes:

```python
res = check_partner(self, partner)  # type: odoo.model.res_partner | int
```

However, it seems the type hint will be used for the `res` variable instead.

**Comment by jcfernandez-890825** [comment]
> However, it seems the type hint will be used for the `res` variable instead.

Yes, I used inline comments on controllers, because Pycharm can't figure it out variable types sometimes.

**Comment by trinhanhngoc** [comment]
@jcfernandez-890825 For the type hint of model dict value https://github.com/odoo-ide/pycharm-odoo/issues/67, I think the syntax will be different from this.

**Comment by jcfernandez-890825** [comment]
> @jcfernandez-890825 For the type hint of model dict value #67, I think the syntax will be different from this.

Ok, but why?

**Comment by trinhanhngoc** [comment]
> > @jcfernandez-890825 For the type hint of model dict value #67, I think the syntax will be different from this.
> 
> Ok, but why?

I am not sure. Maybe I will use [typing.Annotated](https://docs.python.org/3/library/typing.html#typing.Annotated) for it. Example:

```python3
def _prepare_sale_order_line_values(self):
     vals: Annotated[dict, odoo.model.sale_order_line] = {
         'product_id': ...
     }
     return vals
```

**Comment by jcfernandez-890825** [comment]
> Maybe I will use [typing.Annotated](https://docs.python.org/3/library/typing.html#typing.Annotated) for it

I think that might be an overkill, how about using both? The simple `dict`, `typing.Dict`, `typing.Mapping` and this one `typing.Annotated`.

**Comment by trinhanhngoc** [comment]
> > Maybe I will use [typing.Annotated](https://docs.python.org/3/library/typing.html#typing.Annotated) for it
> 
> I think that might be an overkill, how about using both? The simple `dict`, `typing.Dict`, `typing.Mapping` and this one `typing.Annotated`.

Yes, using `typing.Annotated` is a bit verbose. I will think more about this case.

**Comment by mrm-david** [comment]
> > > Maybe I will use [typing.Annotated](https://docs.python.org/3/library/typing.html#typing.Annotated) for it
> > 
> > 
> > I think that might be an overkill, how about using both? The simple `dict`, `typing.Dict`, `typing.Mapping` and this one `typing.Annotated`.
> 
> Yes, using `typing.Annotated` is a bit verbose. I will think more about this case.

I'd gladly use Annotated if it's too hard to come up with a simpler way to type hint.

**Comment by eselimsen** [comment]
Hi @trinhanhngoc 
That's great to hear, thanks.

Not sure how possible it is, but I would love to have multi-form definitions, like we discussed [here](https://github.com/odoo-ide/pycharm-odoo/issues/60#issuecomment-1013746455), and would also want to add something like `model_dict` and `model_self`, if possible.

Those would be particularly useful for getters, or processors, we could just use:
`def get_record(self, vals: "odoo.model_dict_self", partner_vals: "odoo.model_dict.res.partner"): -> "odoo.model_self"`.
I think these may also help on #105

**Comment by trinhanhngoc** [comment]
Hi @eselimsen 

Yes, it's certainly possible. However, we need to be careful in deciding the right syntax for them.

- `odoo.model.res_partner` => record `res_partner`
- `odoo.model_one.res_partner` => singleton record `res_partner`
- `odoo.model_dict.res_partner` => dict values of `res_partner`. If we decide to use this syntax, other IDEs like VSCode will get confused.
- `odoo.model_dict_self` => ???

**Comment by eselimsen** [comment]
> Hi @eselimsen
> 
> Yes, it's certainly possible. However, we need to be careful in deciding the right syntax for them.
> 
> * `odoo.model.res_partner` => record `res_partner`
> * `odoo.model_one.res_partner` => singleton record `res_partner`
> * `odoo.model_dict.res_partner` => dict values of `res_partner`. If we decide to use this syntax, other IDEs like VSCode will get confused.
> * `odoo.model_dict_self` => ???

`_self`s are just shortcuts for "this model", would help especially for long-named models.

I believe standard, dot-separated model names would break IDEs etc, right?
That's one concern I had, but I'm not sure how else we can address this. Can't we consider `odoo.model*` proxy objects that expose magic objets (as also done by Odoo for `odoo.addons.*`, or `plumbum` does for `plumbum.cmd`)?

**Comment by trinhanhngoc** [comment]
@eselimsen 

Dot-separated model names would **NOT** break IDEs but it will lead to a more complicated implementation from point of views of IDEs and Python (in case Odoo implements it in the future).

**Comment by jcfernandez-890825** [comment]
Why don't start with the basic and then build on more complex things?

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 @eselimsen @mrm-david 

The new version 2022.6 has been released with this feature. You can read about it the blog post https://odoo-ide.com/blog/news-1/pycharm-odoo-2022-6-10

**Comment by eselimsen** [comment]
Hi @trinhanhngoc 
Yes, I've been testing it, and it looks great (along with other fix/features).

Thanks for another great update!

**Comment by jcfernandez-890825** [comment]
You really went overboard, this new update has a lot of goodies. You should be called the Santa of Odoo. Once again thank you for your hard work.
