### ISSUE TITLE
Syntax highlight code in <attribute name="t-if">...</attribute>

### ISSUE THREAD

**Issue by trinhanhngoc** [odoo-ide/pycharm-odoo#18]

**Comment by jcfernandez-890825** [comment]
Most of the `<attribute ... >...</attribute>` syntax is interpreted as JS. Here are some examples:
![Screenshot from 2021-09-11 13-46-27](https://user-images.githubusercontent.com/28876647/132956709-1e03e0a8-78c9-4b10-9e8c-0b4f12673810.png)
![Screenshot from 2021-09-11 13-48-47](https://user-images.githubusercontent.com/28876647/132956729-6903128b-cd61-487f-be63-daed33a920d7.png)
![Screenshot from 2021-09-11 13-50-04](https://user-images.githubusercontent.com/28876647/132956761-fe0c41ec-25c2-45da-bbba-b6cdb60f2b79.png)

**Comment by trinhanhngoc** [comment]
Implemented in 2021.2.6

**Comment by jcfernandez-890825** [comment]
Can't wait to see it.
