### ISSUE TITLE
Support for 2021.2

### ISSUE THREAD

**Issue by aqeebimtiaz-bista** [odoo-ide/pycharm-odoo#2]
Hi, I just upgraded PyCharm 2021.1 to 2021.2 & suddenly the PyCharm Odoo plugin just became unsupported.

This is the error message that's been popping up on PyCharm: 

> Plugin 'PyCharm Odoo' (version '4.16') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is PY-212.4746.96

**Comment by trinhanhngoc** [comment]
Hi @aqeebimtiaz-bista ,

The new version has been released with support for PyCharm 2021.2. You can buy it at https://plugins.jetbrains.com/plugin/13499-odoo/ to support the plugin's development.
