### ISSUE TITLE
XML warning when using eval attrib

### ISSUE THREAD

**Issue by jcfernandez-890825** [odoo-ide/pycharm-odoo#38]
When using "Inspect code...", on XML files that use eval attrib, those warnings always arise.
![image](https://user-images.githubusercontent.com/28876647/137955557-b796b982-3de7-4d6b-8a70-f1e7da6a881a.png)

**Comment by trinhanhngoc** [comment]
Thank you!. The fix will be available in the next release 2021.2.9.
