### ISSUE TITLE
`id` field not recognized as valid on Odoo recordsets

### ISSUE THREAD

**Issue by zachwaite** [odoo-ide/pycharm-odoo#4]
Plugin version 2021.2

In many contexts, references to the `id` field of a single member recordset object causes PyCharm to trigger a `PyUnresolvedReferences` warning.

I'd expect the plugin to not warn here since the object being accessed derives from `BaseModel` and has an `id` field. This happens in both Python and xml files.

Example:
![PyCharm-Odoo-plugin_issue_01](https://user-images.githubusercontent.com/6884125/129558852-f92bf5e0-f9fd-45b2-a3b1-f47aecccd0ea.png)

![image](https://user-images.githubusercontent.com/6884125/129559029-791d2500-adbf-4d84-a137-c7a15c8c1cc7.png)

**Comment by trinhanhngoc** [comment]
Hi @zachwaite,

Please attach https://github.com/trinhanhngoc/odoo-stubs to your project to help PyCharm resolve these automatic attributes.

**Comment by zachwaite** [comment]
> Hi @zachwaite,
> 
> Please attach https://github.com/trinhanhngoc/odoo-stubs to your project to help PyCharm resolve these automatic attributes.

I have referenced the parent directory as the content root, which contains odoo, odoo-stubs and my custom addons. Attempting to add odoo-stubs explicitly raises a PyCharm Error about intersecting content entries. I guess the module won't search down that far?

**Comment by trinhanhngoc** [comment]
> > Hi @zachwaite,
> > Please attach https://github.com/trinhanhngoc/odoo-stubs to your project to help PyCharm resolve these automatic attributes.
> 
> I have referenced the parent directory as the content root, which contains odoo, odoo-stubs and my custom addons. Attempting to add odoo-stubs explicitly raises a PyCharm Error about intersecting content entries. I guess the module won't search down that far?

It seems you are structuring your project incorrect. odoo, odoo-stubs and other custom addons paths should be placed as top level in your project, not the parent directory containing them.
