### ISSUE TITLE
Correct references are incorrectly highlighted

### ISSUE THREAD

**Issue by rven** [odoo-ide/pycharm-odoo#6]
![2021-08-19_13-37](https://user-images.githubusercontent.com/8638295/130062242-979e2c7d-fddf-4a89-8324-6a649b7e146f.png)
![2021-08-19_13-38](https://user-images.githubusercontent.com/8638295/130062341-0e48c104-910a-477e-bc01-a1d4bb9d9c88.png)
![2021-08-19_13-47](https://user-images.githubusercontent.com/8638295/130063523-b128cfe9-b237-45cb-b27a-b18574dab009.png)

**Comment by ghost** [comment]
Hi @rven ,

This is so weird. Does this also occurs in other places in your code ?

**Comment by ghost** [comment]
@rven ,

You can try **Invalidate Caches** to see if it resolves the issue:

![Screenshot from 2021-08-19 19-08-59](https://user-images.githubusercontent.com/65052910/130066027-096170cc-a14d-40b6-a04d-c8c1088c34d2.png)

**Comment by rven** [comment]
Hi @ngoctrinh-viindoo 

I tried your suggestion without success.
I also tried already to reset the Odoo code to the latest 14.0 source code, also without success.

Another project does not has this problem at all.

**Comment by ghost** [comment]
> Hi @ngoctrinh-viindoo
> 
> I tried your suggestion without success.
> I also tried already to reset the Odoo code to the latest 14.0 source code, also without success.
> 
> Another project does not has this problem at all.

Are you sure your odoo module is scaffolded properly? Please check if has any typo error in name of file `__init__.py` and `__manifest__.py`. The highlight errors might occur if the containing odoo module was not recognized.

**Comment by ghost** [comment]
Hi @rven 

Have you solved this problem?

**Comment by rven** [comment]
Hi @ngoctrinh-viindoo 

I resolved the issue by completely rebuilding the project.
