### ISSUE TITLE
Autocompletion for selection fields value

### ISSUE THREAD

**Issue by Guenzn** [odoo-ide/pycharm-odoo#9]
A very usefull feature would be auto completion support selection fields values. 
![image](https://user-images.githubusercontent.com/24382867/131105278-5876d810-9624-45ec-bef2-24a585c49525.png)

**Comment by trinhanhngoc** [comment]
I also like this feature, it will be available soon =))

**Comment by trinhanhngoc** [comment]
Hi @Guenzn 

The new version 2021.2.5 has been released with this new feature. Enjoy!

![Screenshot from 2021-09-07 20-48-41](https://user-images.githubusercontent.com/11208291/132356125-79051fdf-81d3-46e8-bfd9-0e54281a1d22.png)
